name: Run Tests on Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  run_tests_on_pull_request:
    env:
      FORCE_COLOR: "true"
      DISPLAY: ":0"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main' Branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install Virtual Frame Buffer Package(xvfb)
        run: sudo apt-get install xvfb
      - name: Create Virtual Display for ChromeDriver to Use
        run: Xvfb :0 -screen 0 1024x768x16 &
      - name: Install Node Dependencies
        run: npm install
      - name: Create rebabel_convert Executable Using PyInstaller
        run: .github/scripts/create_rebabel_convert_executable
      - name: Create Rebabel Electron Executable
        run: npm run make
      - name: Run Jasmine Tests
        run: npm run test:build_agent
